### PR TITLE
New mixins 0.8.7, mixinextras 0.4.1, and ASM 9.7.1

### PR DESCRIPTION
**Pull request by mitchej123**
Bumps UniMix to 0.15.3_mixin.0.8.7, Mixin Extras to 0.4.1, and ASM to 9.7.1

Notes:

- [x] - Pending - Tested in Full GTNH nightly pack 

Previously tested by FalsePattern w/ GTMega and reported to be working

### CODE REVIEW

**Review by unix-supremacist — APPROVED** [review]

**Comment by mitchej123** [comment]
Waiting on getting hodgepodge working with the change in shadow behavior, will set to ready again after that's confirmed working.

**Comment by embeddedt** [comment]
What changed about Shadow behavior? This may break other mods; we need to be careful about that.

**Comment by mitchej123** [comment]
> What changed about Shadow behavior? This may break other mods; we need to be careful about that.

I'm not convinced the shadow behavior was ever supported, or just a side effect.  

Previously if there was `Blah blah = new Blah()` and you did `@Shadow Blah blah = new Something()` it would end up with it being added to the constructor after the initial Blah().  I don't see anything documented indicating this was expected, but it did work.

Now it adds the `new Something()` significantly earlier in the constructor, and the `new Blah()` takes precedence.

Still trying to narrow down what change specifically instigated this, and whether it was intentional, or a bad interact with our patches.  Having some other oddities booting the pack that I haven't tracked down yet either hence the draft status.

**Comment by Roadhog360** [comment]
Yeah. If shadow behavior changed, that would be bad news. But I was under the impression that nothing is really supposed to ever populate shadow fields or functions. It's hard to say what to do in this case because any mods that do this were abusing an unexpected result from mixins instead of using mixins properly, which could have easily achieved the same result.

Then again, we have a certain mod I won't name and probably others that just spam overrides everywhere. So mods not using mixin correctly isn't exactly news.

**Comment by jss2a98aj** [comment]
I think I used the unintended shadow behavior a little bit in BugTorch, though I was not aware it was unintended. I doubt it will introduce any crashes once changed, but I will probably need to fix a few non-criticl mixins.

**Comment by mitchej123** [comment]
Pending some investigation and adjustment of behavior upstream.  Will likely result in a unimix bump.

**Comment by mitchej123** [comment]
Lyfts confirmed the update in Unimix from upstream FabricMixins fixed this.  Will do some additional testing from this PR to ensure everything works properly.

**Review by jss2a98aj — APPROVED** [review]
Everything appears to be working fine in my setup with these changes. No crashes or incorrect behavior.

**Pull request merged**
