### PR TITLE
Update MixinExtras to latest

### LINKED ISSUE #14: Update MixinExtras to latest rc
Newer version of MixinExtras implement improvements to sugar features like `@Local` and `@Share` which are very useful. Along with these features there are also other improvements to the library itself.

Latest version is:
https://github.com/LlamaLad7/MixinExtras/releases/tag/0.2.0-rc.5

### PR DESCRIPTION
**Pull request by drori200**
Closes #14

### CODE REVIEW

**Comment by drori200** [comment]
Currently with these changes early mixins loaded with GTNH's `IEarlyMixinLoader` aren't able to be loaded. Can't find the reason for this beside this error: 
```
error: cannot access net.minecraftforge.fml.relauncher.IFMLLoadingPlugin
public class HavenCoreEarlyMixins implements IFMLLoadingPlugin, IEarlyMixinLoader {
       ^
  class file for net.minecraftforge.fml.relauncher.IFMLLoadingPlugin not found```

**Comment by drori200** [comment]
This is the contents of the class:
```java
package net.HavenCore.HavenCorePublic;

import java.io.IOException;
import java.util.*;
import java.util.logging.Logger;

import com.gtnewhorizon.gtnhmixins.IEarlyMixinLoader;

import cpw.mods.fml.relauncher.IFMLLoadingPlugin;

public class HavenCoreEarlyMixins implements IFMLLoadingPlugin, IEarlyMixinLoader {
	private Logger logger = Logger.getLogger("HavenCoreEarlyMixins");
	@Override
	public String getMixinConfig() {
		return "mixin." + Tags.MODID + ".early.json";
	}

    @Override
    public List<String> getMixins(Set<String> loadedCoreMods) {
        final List<String> mixins = new ArrayList<>();
        final List<String> notLoading = new ArrayList<>();
        for (Mixins mixin : Mixins.values()) {
            if (mixin.phase == Mixins.Phase.EARLY) {
                if (mixin.shouldLoad(loadedCoreMods, Collections.emptySet())) {
                    mixins.addAll(mixin.mixinClasses);
                } else {
                    notLoading.addAll(mixin.mixinClasses);
                }
            }
        }
        System.out.println("Not loading the following EARLY mixins: {}"+ notLoading.toString());
        return mixins;
    }
	@Override
	public String[] getASMTransformerClass() {
		return null;
	}

	@Override
	public String getModContainerClass() {
		return null;
	}

	@Override
	public String getSetupClass() {
		return null;
	}

	@Override
	public void injectData(Map<String, Object> data) {
	}

	@Override
	public String getAccessTransformerClass() {
		return null;
	}
}```

**Comment by drori200** [comment]
After a bit more checking it is the usage of `IFMLLoadingPlugin` itself which is problematic

**Comment by drori200** [comment]
After trying to use standalone GTNHMixin it seems the problem resides in the UniMixins mod.
The class i posted above loads fine with GTNHMixins but fails when using UniMixins.

**Comment by drori200** [comment]
by the looks of it, the compat module is the problem when using the `-all` jar. This means that the remapping to 1.7.10 with the module isn't working

**Review by mitchej123 — APPROVED** [review]

**Review by unix-supremacist — APPROVED** [review]

**Pull request merged**
