### PR TITLE
Remove MixinExtras from GTNHMixin

### PR DESCRIPTION
**Pull request by drori200**
As per @mitchej123 's request i have removed MixinExtras from the GTNHMixin module

### CODE REVIEW

**Review by mitchej123 — APPROVED** [review]

**Comment by makamys** [comment]
This causes mods that used the old package to silently break, which isn't exactly ideal. Perhaps we could let the compat module keep it defined at runtime (using either `defineClass` or a synthesizing class transformer.) MixinExtras 0.1.1 is only 22 classes weighing 31 KB, so it should be fairly cheap.

**Comment by mitchej123** [comment]
> This causes mods that used the old package to silently break, which isn't exactly ideal. Perhaps we could let the compat module keep it defined at runtime (using either `defineClass` or a synthesizing class transformer.) MixinExtras 0.1.1 is only 22 classes weighing 31 KB, so it should be fairly cheap.

I'm not opposed, but also not nearly familiar enough with a class transformer to make that work.  The only known mods using it were on NH and we went through and cleaned up all references to it.

**Comment by makamys** [comment]
I can still find a few stray references to the old package name [on GitHub](https://github.com/search?q=com.gtnewhorizon.mixinextras&type=code). But even if they were all updated, my reasoning is that people use GTNH mods outside GTNH, and may forget to update them while updating UniMixins, resulting in much confusion for everyone.

I'll give it a try.

**Comment by mitchej123** [comment]
Ah nice idea to search github for it, didn't think of that - just looked at our repos.

**Comment by makamys** [comment]
The class generator seems to be working like a charm. Ironically the only hiccup was a Mixingasm incompatibility, but I sorted it out.

I'll push it after this is merged.

**Review by makamys — APPROVED** [review]

**Pull request merged**
